version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: django_backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn marketplace.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    env_file:
      - ./frontend/.env
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: reverse_proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro

volumes:
  static_volume:
