# Generated by Django 4.2.7 on 2025-08-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_seller_approval', 'Pending Seller Approval'), ('seller_approved', 'Approved by Seller'), ('seller_rejected', 'Rejected by Seller'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending_seller_approval', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('pending_seller_approval', 'Pending Seller Approval'), ('seller_approved', 'Approved by Seller'), ('seller_rejected', 'Rejected by Seller'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=30),
        ),
    ]
