# Generated by Django 4.2.7 on 2025-08-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_average_rating_product_total_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending Sale'), ('sold', 'Sold'), ('expired', 'Expired'), ('inactive', 'Inactive')], default='available', max_length=20),
        ),
    ]
