# Generated by Django 4.2.7 on 2025-08-15 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0006_alter_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether this product has been verified by an admin",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for rejection if product was rejected",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="verification_notes",
            field=models.TextField(
                blank=True, help_text="Admin notes about the verification", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="verified_at",
            field=models.DateTimeField(
                blank=True, help_text="When the product was verified", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who verified this product",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("sold", "Sold"),
                    ("expired", "Expired"),
                    ("inactive", "Inactive"),
                    ("pending_verification", "Pending Verification"),
                ],
                default="pending_verification",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ProductReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("irrelevant", "Irrelevant Product"),
                            ("harassment", "Harassment"),
                            ("spam", "Spam"),
                            ("inappropriate", "Inappropriate Content"),
                            ("fake", "Fake Product"),
                            ("fraud", "Fraud/Scam"),
                            ("duplicate", "Duplicate Listing"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Please describe the issue"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about this report", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="products.product",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "product_reports",
                "ordering": ["-created_at"],
                "unique_together": {("reporter", "product")},
            },
        ),
    ]
