# Generated by Django 4.2.7 on 2025-08-11 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('both', 'Buyer & Seller')], default='buyer', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('not_required', 'Not Required')], default='not_required', max_length=15),
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_front', models.ImageField(upload_to='verification/id_cards/front/')),
                ('id_card_back', models.ImageField(upload_to='verification/id_cards/back/')),
                ('additional_documents', models.FileField(blank=True, null=True, upload_to='verification/additional/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes from user')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin feedback')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
