# Generated by Django 4.2.7 on 2025-08-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status_alter_orderstatus_status'),
        ('users', '0002_user_account_approved_user_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='orders.order'),
        ),
    ]
