# Generated by Django 4.2.7 on 2025-08-13 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status_alter_orderstatus_status'),
        ('users', '0003_userrating_order'),
    ]

    operations = [
        # First remove the old unique constraint
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together=set(),
        ),
        # Make order field non-nullable
        migrations.AlterField(
            model_name='userrating',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='orders.order'),
        ),
        # Add the new unique constraint with order included
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('from_user', 'to_user', 'order')},
        ),
    ]
